#+TITLE: Spacemacs Configuration File
#+AUTHOR: gfanton
#+BABEL: :cache yes
#+STARTUP: indent hideblocks
#+PROPERTY: header-args :tangle yes :comments org
#+SETUPFILE: ~/.spacemacs.d/org-html-themes/setup/theme-readtheorg.setup

My dotspacemacs configuration for [[https://github.com/syl20bnr/spacemacs][SpaceMacs_]]

* SPACEMACS INITIALIZATION

Initialization function.
This function is called at the very startup of Spacemacs initialization
before layers configuration.

#+BEGIN_SRC emacs-lisp :exports none
  (defun dotspacemacs/init ()
    "Initialization function.
  This function is called at the very startup of Spacemacs initialization
  before layers configuration.
  You should not put any user code in there besides modifying the variable
  values."
    ;; This setq-default sexp is an exhaustive list of all the supported
    ;; spacemacs settings.
    (setq-default
#+END_SRC

** editing style

One of `vim', `emacs' or `hybrid'. Evil is always enabled but if the
variable is `emacs' then the `holy-mode' is enabled at startup. `hybrid'
uses emacs key bindings for vim's insert mode, but otherwise leaves evil
unchanged. (default 'vim)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-editing-style 'hybrid
#+END_SRC

** verbose loading

If non nil output loading progress in `*Messages*' buffer. (default nil)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-verbose-loading nil
#+END_SRC

** startup page
*** banner

Specify the startup banner. Default value is `official', it displays
the official spacemacs logo. An integer value is the index of text
banner, `random' chooses a random text banner in `core/banners'
directory. A string value must be a path to an image format supported
by your Emacs build.
If the value is nil then no banner is displayed. (default 'official)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-startup-banner 'official
#+END_SRC

*** lists

List of items to show in the startup buffer. If nil it is disabled.
Possible values are: `recents' `bookmarks' `projects'.
(default '(recents projects))

#+BEGIN_SRC emacs-lisp
  dotspacemacs-startup-lists '(recents projects)
#+END_SRC

** themes

List of themes, the first of the list is loaded when spacemacs starts.
Press <SPC> T n to cycle to the next theme in the list (works great
with 2 themes variants, one dark and one light)

#+BEGIN_SRC emacs-lisp
    dotspacemacs-themes '(molokai
                          monokai)
#+END_SRC

** cursor-color

If non nil the cursor color matches the state color.

#+BEGIN_SRC emacs-lisp
  dotspacemacs-colorize-cursor-according-to-state t
#+END_SRC

** font

Default font. `powerline-scale' allows to quickly tweak the mode-line
size to make separators look not too crappy.

#+BEGIN_SRC emacs-lisp
  dotspacemacs-default-font '("Source Code Pro"
                              :size 13
                              :weight bold
                              :width normal
                              :powerline-scale 1.1)
#+END_SRC

** leader key

*** the leader key

#+BEGIN_SRC emacs-lisp
  dotspacemacs-leader-key "SPC"
#+END_SRC

*** emacs leader key

The leader key accessible in `emacs state' and `insert state'
(default "M-m")

#+BEGIN_SRC emacs-lisp
  dotspacemacs-emacs-leader-key "M-m"
#+END_SRC

*** mode leader key

Major mode leader key is a shortcut key which is the equivalent of
pressing `<leader> m`. Set it to `nil` to disable it. (default ",")

#+BEGIN_SRC emacs-lisp
  dotspacemacs-major-mode-leader-key ","
#+END_SRC

*** major mode emacs leader key

Major mode leader key accessible in `emacs state' and `insert state'.
(default "C-M-m)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-major-mode-emacs-leader-key "C-M-m"
#+END_SRC

** command key

The command key used for Evil commands (ex-commands) and
Emacs commands (M-x).
By default the command key is `:' so ex-commands are executed like in Vim
with `:' and Emacs commands are executed with `<leader> :'.

#+BEGIN_SRC emacs-lisp
  dotspacemacs-command-key ":"
#+END_SRC

If non nil `Y' is remapped to `y$'. (default t)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-remap-Y-to-y$ t
#+END_SRC

** auto-save

Location where to auto-save files. Possible values are `original' to
auto-save the file in-place, `cache' to auto-save the file to another
file stored in the cache directory and `nil' to disable auto-saving.
(default 'cache)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-auto-save-file-location 'cache
#+END_SRC

** ido

If non nil then `ido' replaces `helm' for some commands. For now only
`find-files' (SPC f f), `find-spacemacs-file' (SPC f e s), and
`find-contrib-file' (SPC f e c) are replaced. (default nil)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-use-ido nil
#+END_SRC

** helm
*** helm resize

If non nil, `helm' will try to miminimize the space it uses. (default nil)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-helm-resize nil
#+END_SRC

*** helm header

if non nil, the helm header is hidden when there is only one source.
(default nil)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-helm-no-header nil
#+END_SRC

*** helm position

define the position to display `helm', options are `bottom', `top',
`left', or `right'. (default 'bottom)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-helm-position 'bottom
#+END_SRC

** paste micro-state

If non nil the paste micro-state is enabled. When enabled pressing `p`
several times cycle between the kill ring content. (default nil)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-enable-paste-micro-state nil
#+END_SRC

** which-key
*** delay

Which-key delay in seconds. The which-key buffer is the popup listing
the commands bound to the current keystroke sequence. (default 0.4)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-which-key-delay 0.4
#+END_SRC

*** position

Which-key frame position. Possible values are `right', `bottom' and
`right-then-bottom'. right-then-bottom tries to display the frame to the
right; if there is insufficient space it displays it at the bottom.
(default 'bottom)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-which-key-position 'bottom
#+END_SRC

** loading-progress-bar

If non nil a progress bar is displayed when spacemacs is loading. This
may increase the boot time on some systems and emacs builds, set it to
nil to boost the loading time. (default t)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-loading-progress-bar t
#+END_SRC

** fullscreen
*** startup

If non nil the frame is fullscreen when Emacs starts up. (default nil)
(Emacs 24.4+ only)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-fullscreen-at-startup nil
#+END_SRC

*** toggle native

If non nil `spacemacs/toggle-fullscreen' will not use native fullscreen.
Use to disable fullscreen animations in OSX. (default nil)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-fullscreen-use-non-native nil
#+END_SRC

** frame
*** startup

If non nil the frame is maximized when Emacs starts up.
Takes effect only if `dotspacemacs-fullscreen-at-startup' is nil.
(default nil) (Emacs 24.4+ only)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-maximized-at-startup nil
#+END_SRC

** transparency
*** active

A value from the range (0..100), in increasing opacity, which describes
the transparency level of a frame when it's active or selected.
Transparency can be toggled through `toggle-transparency'. (default 90)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-active-transparency 90
#+END_SRC

*** inactive

A value from the range (0..100), in increasing opacity, which describes
the transparency level of a frame when it's inactive or deselected.
Transparency can be toggled through `toggle-transparency'. (default 90)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-inactive-transparency 90
#+END_SRC

** unicode

If non nil unicode symbols are displayed in the mode line. (default t)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-mode-line-unicode-symbols t
#+END_SRC

** scrolling

If non nil smooth scrolling (native-scrolling) is enabled. Smooth
scrolling overrides the default behavior of Emacs which recenters the
point when it reaches the top or bottom of the screen. (default t)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-smooth-scrolling t
#+END_SRC

** smartparens

If non-nil smartparens-strict-mode will be enabled in programming modes.
(default nil)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-smartparens-strict-mode nil
#+END_SRC

** delimiters
*** highlight

Select a scope to highlight delimiters. Possible values are `any',
`current', `all' or `nil'. Default is `all' (highlight any scope and
emphasis the current one). (default 'all)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-highlight-delimiters 'all
#+END_SRC

** server

If non nil advises quit functions to keep server open when quitting.
(default nil)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-persistent-server nil
#+END_SRC

** search tools

List of search tool executable names. Spacemacs uses the first installed
tool of the list. Supported tools are `ag', `pt', `ack' and `grep'.
(default '("ag" "pt" "ack" "grep"))

#+BEGIN_SRC emacs-lisp
  dotspacemacs-search-tools '("ag" "pt" "ack" "grep")
#+END_SRC

** package repository

The default package repository used if no explicit repository has been
specified with an installed package.
Not used for now. (default nil)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-default-package-repository nil
#+END_SRC

#+BEGIN_SRC emacs-lisp :exports none
     ))
#+END_SRC


* LAYERS CONFIGURATION

Layers configuration declaration.

#+BEGIN_SRC emacs-lisp :exports none
  (defun dotspacemacs/layers ()
    "Configuration Layers declaration."
    (setq-default
#+END_SRC

** Distribution

Base distribution to use. This is a layer contained in the directory
`+distribution'. For now available distributions are `spacemacs-base'
or `spacemacs'. (default 'spacemacs)

#+BEGIN_SRC emacs-lisp 
  dotspacemacs-distribution 'spacemacs
#+END_SRC

** Layers

Use <SPC f e R> (Vim style) or <M-m f e R> (Emacs style) to install them.

#+BEGIN_SRC emacs-lisp :exports none
  dotspacemacs-configuration-layers
  '(
#+END_SRC

*** OSX

While this layer enables common OSX bindings, it does not implement OSX
navigation keybindings. Spacemacs is meant to be used with evil, and we
encourage you to do so :)

#+BEGIN_SRC emacs-lisp
osx
#+END_SRC

*** Auto-Completion

This layer provides auto-completion to Spacemacs.
The following completion engines are supported:
- [[http://company-mode.github.io/][company]]
- [[http://auto-complete.org/][auto-complete]]

Snippets are supported via [[https://github.com/capitaomorte/yasnippet][yasnippet]] and [[https://github.com/abo-abo/auto-yasnippet][auto-yasnippet]].
This layer also configures =hippie-expand=.

#+BEGIN_SRC emacs-lisp
  (auto-completion :variables
                   auto-completion-return-key-behavior 'complete
                   auto-completion-tab-key-behavior 'cycle
                   auto-completion-complete-with-key-sequence nil
                   auto-completion-private-snippets-directory "~/.spacemacs.d/snippets")
#+END_SRC

*** Better-Defaults

This layer enhances the default commands of Emacs and is primarily intended to
be used with the =emacs= editing style as it does not change anything in the Vim
key bindings.

However the =emacs= editing style is not required, you can still use this layer
while you are using the =vim= editing style if you have some kind of mixed
style.

The commands defined in this layer are taken from various sources like [[https://github.com/bbatsov/prelude][Prelude]].

#+BEGIN_SRC emacs-lisp
  better-defaults
#+END_SRC

*** Tmux

This is an extension to support [[https://github.com/Keithbsmiley/evil-tmux-navigator][evil-tmux-navigator]].

#+BEGIN_SRC emacs-lisp
  tmux
#+END_SRC

*** Floobits

This layer adds support for peer programming tool [[https://github.com/Floobits/floobits-emacs][floobits]].

#+BEGIN_SRC emacs-lisp
  floobits
#+END_SRC

*** Colors

This layer colors your life with:
- [[https://github.com/Fanael/rainbow-identifiers][rainbow identifiers]] mode will colorize each variables and functions with an
  almost unique color. The keywords and the declaration of function colors are
  disabled in order to make the colorized variables and functions stand out.
- [[https://julien.danjou.info/projects/emacs-packages][rainbow mode]] displays strings representing colors with the color they
  represent as background.
- [[https://github.com/syl20bnr/nyan-mode][nyan mode]] display a Nyan cat progress bar in the mode-line.

#+BEGIN_SRC emacs-lisp
  (colors :variables
          ;; colors-enable-rainbow-identifiers t
          ;; colors-enable-nyan-cat-progress-bar t
          )
#+END_SRC

*** Jabber

This layer adds keybindings for jabber.el. jabber.el is a Jabber (XMPP) client for Emacs

#+BEGIN_SRC emacs-lisp
  jabber
#+END_SRC

*** Emacs-Lisp

This layer gathers all the configuration related to emacs-lisp. This should
always be in your dotfile, it is not recommended to uninstall it.

#+BEGIN_SRC emacs-lisp
  emacs-lisp
#+END_SRC

*** Vim-Empty-lines

This layer is a drop-in replacement for the =vi-tilde-fringe= mode, for those
who desire behaviour closer to =vim='s.

It has better compatibility with retina displays, as it uses a text overlay
using your font, rather than a pixel-art tilde. The empty line indicators are
overlaid in within the buffer as in =vim=, and not in the fringe. The indicator
behaviour with trailing empty lines matches =vim='s behaviour.

For details, see the [[https://github.com/jmickelin/vim-empty-lines-mode][vim-empty-lines-mode]] repository.   

#+BEGIN_SRC emacs-lisp
  vim-empty-lines
#+END_SRC

*** Python

This layer adds support for the Python language.

#+BEGIN_SRC emacs-lisp
  python
#+END_SRC

*** Ruby

This layer aims at providing support for the Ruby language using
[[https://github.com/zenspider/enhanced-ruby-mode][enh-ruby-mode]] and [[https://github.com/dgutov/robe][robe-mode]].

#+BEGIN_SRC emacs-lisp
  ruby
#+END_SRC

*** Themes

This simple contribution layer is an example. It installs around 100 themes
for Emacs. You can try them easily by invoking helm-themes with: ~<SPC> T h~.

#+BEGIN_SRC emacs-lisp
  themes-megapack
#+END_SRC

*** Restclient

This is a package that lets you have a REPL-like interface
for http requests. Full documentation and examples can be found in the
package's [[https://github.com/pashky/restclient.el][GitHub Page]].

#+BEGIN_SRC emacs-lisp
  restclient
#+END_SRC

*** C-C++

This layer adds configuration for C/C++ language as well support for [[http://www.cmake.org/][CMake]]
scripts.

#+BEGIN_SRC emacs-lisp
  c-c++
#+END_SRC

*** Cscope

This layer provides bindings for using [[http://cscope.sourceforge.net][Cscope]] and [[https://github.com/portante/pycscope][PyCscope]] in Spacemacs.

=Cscope= provides indexing and searching capabilities for C and C++ code.
=PyCscope= extends these capabilities for Python code as well. See
[[https://github.com/OpenGrok/OpenGrok/wiki/Comparison-with-Similar-Tools][here]] for a comparison between =Cscope= and other similar tools (such as gtags).

#+BEGIN_SRC emacs-lisp
  cscope
#+END_SRC

*** Php

This layer adds PHP language support to Spacemacs.

#+BEGIN_SRC emacs-lisp
  php
#+END_SRC

*** Html

This layer adds support for editing HTML and CSS.

#+BEGIN_SRC emacs-lisp
  html
#+END_SRC

*** Sql

This layer adds key bindings and configuration for =sql-mode=, which manages
interactive SQL buffers and highlights a wide range of SQL dialects.

#+BEGIN_SRC emacs-lisp
  sql
#+END_SRC

*** Java

This layer adds support for the Java language using the [[http://eclim.org][Eclim]] client/server.

#+BEGIN_SRC emacs-lisp
  java
#+END_SRC

*** Javascript

This layer adds support for the JavaScript language using [[https://github.com/mooz/js2-mode][js2-mode]].

#+BEGIN_SRC emacs-lisp
  javascript
#+END_SRC

*** Clojure

This layer adds support for [[http://clojure.org][Clojure]] language using [[https://github.com/clojure-emacs/cider][CIDER]].

#+BEGIN_SRC emacs-lisp
  clojure
#+END_SRC

*** Latex

This layer adds support for LaTeX files with [[https://savannah.gnu.org/projects/auctex/][AucTeX]].

#+BEGIN_SRC emacs-lisp
  latex
#+END_SRC

*** Django

This layer adds support for the Python [[https://www.djangoproject.com/][Django]] framework via [[https://github.com/davidmiller/pony-mode][pony-mode]].

#+BEGIN_SRC emacs-lisp
  django
#+END_SRC

*** Dockerfile

This layer provides syntax highlighting and build functionality for Docker files.

#+BEGIN_SRC emacs-lisp
  dockerfile
#+END_SRC

*** Semantic

CEDET is a *C*ollection of *E*macs *D*evelopment *E*nvironment *T*ools written
with the end goal of creating an advanced development environment in Emacs.
CEDET includes common features such as intelligent completion, source code
navigation, project management, code generation with templates. CEDET also
provides a framework for working with programming languages; support for new
programming languages can be added and use CEDET to provide IDE-like features.
This framework is called Semantic.

Semantic is a package that provides a framework for writing parsers. Parsing is
a process of analyzing source code based on programming language syntax. The
packages relies on Semantic for analyzing source code and uses its results to
perform smart code refactoring that based on code structure of the analyzed
language, instead of plain text structure. Semantic is the core of CEDET.

#+BEGIN_SRC emacs-lisp
  semantic
#+END_SRC

*** Git

This layers adds extensive support for [[http://git-scm.com/][git]].

#+BEGIN_SRC emacs-lisp
  git
#+END_SRC

*** Github

This layers adds support for [[http://github.com][Github]].

#+BEGIN_SRC emacs-lisp
  github
#+END_SRC

*** Version-Control

This layers adds general configuration for [[http://www.gnu.org/software/emacs/manual/html_node/emacs/Version-Control.html][Emacs VC]].
It should work with all VC backends such as Git, Mercurial, Bazaar, SVN, etc...

#+BEGIN_SRC emacs-lisp
  version-control
#+END_SRC

*** Markdown

This layer adds markdown support to Spacemacs.

#+BEGIN_SRC emacs-lisp
  markdown
#+END_SRC

*** Org

This layer enables  [[http://orgmode.org/][org mode]] for Spacemacs.

#+BEGIN_SRC emacs-lisp
  org
#+END_SRC

*** Shell

This layer configures the various shells available in Emacs.

#+BEGIN_SRC emacs-lisp
  (shell :variables
         shell-default-height 30
         shell-default-position 'bottom
         shell-default-shell 'term
         shell-default-term-shell "/bin/zsh")
#+END_SRC

*** Spell-Checking

This layer provides spell checking using [[http://www-sop.inria.fr/members/Manuel.Serrano/flyspell/flyspell.html][Flyspell]].

#+BEGIN_SRC emacs-lisp
  spell-checking
#+END_SRC

*** Syntax-Checking

This layer provides on the fly syntax checking using [[http://www.flycheck.org/][Flycheck]].

#+BEGIN_SRC emacs-lisp
  syntax-checking
#+END_SRC

*** Eyebrowse

This layer adds [[https://i3wm.org/][i3wm]] like workspaces thanks to the [[https://github.com/wasamasa/eyebrowse][eyebrowse]] package.

Once the layer is activated a new number is added to the right side of the
mode-line. This number corresponds to the currently active workspace number.

At startup, the workspace number 1 is active. Switching to a workspace will
create it if it does not exist. For instance at startup you can press
~SPC W 2~ to create the workspace 2.

The key bindings are registered in a micro-state displayed in the minibuffer.
The docstring of the micro-state displays the existing workspaces and the
currently active workspace has square brackets. Since this is a micro-state it
is possible to just preview a workspace, for instance press ~SPC W 2~ to see
what's on the workspace 2 then press ~TAB~ to go back to the previously
activated workspace.

It is also possible to give a label to a the current workspace by pressing
~r~ in the micro-state.

#+BEGIN_SRC emacs-lisp
  eyebrowse
#+END_SRC

#+BEGIN_SRC emacs-lisp :exports none
  )   
#+END_SRC

** Layer Path

List of additional paths where to look for configuration layers.
Paths must have a trailing slash (i.e. `~/.mycontribs/')

#+BEGIN_SRC emacs-lisp
  dotspacemacs-configuration-layer-path '("~/.spacemacs.d/layers/")
#+END_SRC

** Packages
*** additional packages

List of configuration layers to load. If it is the symbol `all' instead
of a list then all discovered layers will be installed.
List of additional packages that will be installed without being
wrapped in a layer. If you need some configuration for these
packages then consider to create a layer, you can also put the
configuration in `dotspacemacs/config'.


#+BEGIN_SRC emacs-lisp :exports none
dotspacemacs-additional-packages '(
#+END_SRC

**** Docker

=Docker= is an open platform for building, shipping and running distributed
applications. It gives programmers, development teams and operations engineers
the common toolbox they need to take advantage of the distributed and networked
nature of modern applications.

***** docker-mode

Emacs interface to Docker

#+BEGIN_SRC emacs-lisp
  docker
#+END_SRC

***** docker-tramp

Docker-Tramp offers a TRAMP method for Docker containers.

#+BEGIN_SRC emacs-lisp
  docker-tramp
#+END_SRC

**** EDBI

This program connects the database server through Perl's DBI, and provides
DB-accessing API and the simple management UI.

#+BEGIN_SRC emacs-lisp
  edbi
#+END_SRC

**** Bookmark+

The internal bookmark format (data structure) used by Bookmark+ is compatible
with that of vanilla GnuEmacs. It extends that structure in new ways, to
accommodate new bookmark types.

#+BEGIN_SRC emacs-lisp
   bookmark+
#+END_SRC

**** Dash

Dash is an API Documentation Browser and Code Snippet Manager. dash-at-point
make it easy to search the word at point with Dash.

#+BEGIN_SRC emacs-lisp
  dash-at-point
#+END_SRC

**** Skeletor

=Skeletor= provides project templates for Emacs. It also automates the mundane
parts of setting up a new project like version control, licenses and tooling.

=Skeletor= comes with a number of predefined templates and allows you to easily
create your own.

#+BEGIN_SRC emacs-lisp
  skeletor
#+END_SRC

**** SSH Tunnels

This package lets you run and kill SSH tunnels. 
Set the variable ssh-tunnels-configurations, e.g.:

#+BEGIN_SRC emacs-lisp :startup nohideblocks :tangle no
  (setq ssh-tunnels-configurations
        '((:name "my tunnel"
                 :local-port 1234
                 :remote-port 3306
                 :login "me@host")))
#+END_SRC

#+BEGIN_SRC emacs-lisp
  ssh-tunnels
#+END_SRC

**** Impatient Mode

impatient-mode is a minor mode that publishes the live buffer through the local
simple-httpd server under /imp/<buffer-name>. To unpublish a buffer, toggle
impatient-mode off.

#+BEGIN_SRC emacs-lisp
  impatient-mode
#+END_SRC

**** Simple Httpd

A simple Emacs web server.

#+BEGIN_SRC emacs-lisp
  simple-httpd
#+END_SRC

#+BEGIN_SRC emacs-lisp :exports none
)
#+END_SRC

*** excluded packages

A list of packages and/or extensions that will not be install and loaded.

#+BEGIN_SRC emacs-lisp
  dotspacemacs-excluded-packages '()
#+END_SRC

*** orphan-packages 

If non-nil spacemacs will delete any orphan packages, i.e. packages that
are declared in a layer which is not a member of
the list `dotspacemacs-configuration-layers'. (default t)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-delete-orphan-packages t
#+END_SRC

#+BEGIN_SRC emacs-lisp :exports none
))
#+END_SRC


* USER CONFIGURATION
** User Initialization

Initialization function for user code. It is called immediately after
`dotspacemacs/init'.

#+BEGIN_SRC emacs-lisp :exports none
  (defun dotspacemacs/user-init ()
    "Initialization function for user code.
  It is called immediately after `dotspacemacs/init'."
#+END_SRC

*** Sudo

Allow to switch from current user to sudo when browsind `dired' buffers.
To activate and swit with "C-c C-s" just put in your .emacs:

#+BEGIN_SRC emacs-lisp
  ;;; dired-toggle-sudo.el --- Browse directory with sudo privileges.
  ;; Copyright © 2011 Sebastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>
  ;; Author: Sebastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>
  ;; Keywords: emacs, dired
  ;; Created: 2011-07-06
  ;; Last changed: 2012-10-02 01:29:17
  ;; Licence: WTFPL, grab your copy here: http://sam.zoy.org/wtfpl/

  (eval-when-compile (require 'files))
  (eval-when-compile (require 'tramp))
  (eval-when-compile (require 'dired))

  (defun dired-toggle-sudo-internal (path &optional sudo-user)
    "Convert PATH to its sudoed version. root is used by default
  unless SUDO-USER is provided."
    (let* ((file-vec (or (ignore-errors (tramp-dissect-file-name
                                         path))
                         (tramp-dissect-file-name
                          (concat "/:" path) 1)))
           (method  (tramp-file-name-method file-vec))
           (user (tramp-file-name-user file-vec))
           (host  (tramp-file-name-host file-vec))
           (localname (expand-file-name
                       (tramp-file-name-localname file-vec))))
      (when (string= system-name host)
        (setq host nil))
      (cond
       ;; remote directory -> sudo
       ((and host (string= method "scp"))
        (setq method "sudo" user sudo-user))
       ;; remote directory -> normal
       ((and host (string= method "sudo"))
        (setq method "scp" user nil))
       ;; Local directory -> normal
       ((and (not host) (string= method "scp"))
        (setq method "sudo"))
       ;; Local directory -> sudo
       ((and (not host) (string= method "sudo"))
        (setq method nil user sudo-user))
       ;; Local directory -> normal
       (t
        (setq method "sudo" user sudo-user)))
      (replace-regexp-in-string
       "^/:/" "/"
       (tramp-make-tramp-file-name method user host localname))))

  (defun dired-toggle-sudo-find (fname)
    "Create a new buffer for file name FNAME."
    (let ((save-point (point)))
      (find-alternate-file fname)
      (goto-char save-point)))

  ;;;###autoload
  (defun dired-toggle-sudo (&optional sudo-user)
    "Reopen current file or dired buffer with sudo.

  If SUDO-USER is nil assume root.

  If called with `universal-argument' (C-u), ask for username.
  "
    (interactive "P")
    (let* ((fname (or buffer-file-name
                      dired-directory))
           (sudo-user (if current-prefix-arg
                          (read-string "Username: ")
                        sudo-user))
           (orig (current-buffer)))
      (when fname
        (setq fname (dired-toggle-sudo-internal fname sudo-user))
        (if (not (eq major-mode 'dired-mode))
            (dired-toggle-sudo-find fname)
          (kill-buffer orig)
          (dired fname)))))

  (define-key dired-mode-map (kbd "C-c C-s") 'dired-toggle-sudo)
  (eval-after-load 'tramp
   '(progn
      ;; Allow to use: /sudo:user@host:/path/to/file
      (add-to-list 'tramp-default-proxies-alist
       '(".*" "\\`.+\\'" "/ssh:%h:"))))
#+END_SRC

#+BEGIN_SRC emacs-lisp :exports none
    )
#+END_SRC

** User Configuration

Configuration function for user code. This function is called at the very end of
Spacemacs initialization after layers configuration.

#+BEGIN_SRC emacs-lisp :exports none
  (defun dotspacemacs/user-config ()
    "Configuration function for user code.
       This function is called at the very end of Spacemacs initialization after
       layers configuration."
#+END_SRC

*** regexp

I prefer to use PCRE REGEX engine instead

#+BEGIN_SRC emacs-lisp
  (pcre-mode)
  (custom-set-variables
           '(vr/engine (quote pcre2el)))
#+END_SRC

*** PowerLine

Set `Powerline' default separator.

#+BEGIN_SRC emacs-lisp
  (setq powerline-default-separator 'arrow)
#+END_SRC

*** Skeletor

=Skeletor= provides project templates for Emacs. It also automates the mundane
parts of setting up a new project like version control, licenses and tooling.
=Skeletor= comes with a number of predefined templates and allows you to easily
create your own.

#+BEGIN_SRC emacs-lisp
  (setq skeletor-project-directory "~/.spacemacs.d/project-skeletons")
#+END_SRC

*** projectile

**** switch project action

With this setting, once you have selected your project, the top-level directory
of the project is immediately opened for you in a dired buffer.

#+BEGIN_SRC emacs-lisp
  (setq projectile-switch-project-action 'projectile-dired)
#+END_SRC

**** exclude tramp

Exclude projectile on remote connection

#+BEGIN_SRC emacs-lisp
  (defadvice projectile-on (around exlude-tramp activate)
    (unless  (--any? (and it (file-remote-p it))
                     (list
                      (buffer-file-name)
                      list-buffers-directory
                      default-directory))
      ad-do-it))
#+END_SRC

*** windmove

Windmove lets you move point from window to window using Shift and the arrow keys.

#+BEGIN_SRC emacs-lisp
  (when (fboundp 'windmove-default-keybindings)
    (windmove-default-keybindings))
#+END_SRC

Make windmove work in org-mode

#+BEGIN_SRC emacs-lisp
  (add-hook 'org-shiftup-final-hook 'windmove-up)
  (add-hook 'org-shiftleft-final-hook 'windmove-left)
  (add-hook 'org-shiftdown-final-hook 'windmove-down)
  (add-hook 'org-shiftright-final-hook 'windmove-right)
#+END_SRC

*** Org

Hotfix for org problems

#+BEGIN_SRC emacs-lisp
  (org-reload)
#+END_SRC

#+BEGIN_SRC emacs-lisp :exports none
    )
#+END_SRC   
