#+TITLE: Spacemacs Configuration File
#+AUTHOR: gfanton
#+BABEL: :cache yes
#+STARTUP: indent hideblocks
#+PROPERTY: header-args :tangle yes :comments org
#+SETUPFILE: ~/.spacemacs.d/org-html-themes/setup/theme-readtheorg.setup

[[https://github.com/syl20bnr/spacemacs][file:https://cdn.rawgit.com/syl20bnr/spacemacs/442d025779da2f62fc86c2082703697714db6514/assets/spacemacs-badge.svg]]

My dotspacemacs configuration for [[https://github.com/syl20bnr/spacemacs][SpaceMacs_]]

* SPACEMACS INITIALIZATION

Initialization function.
This function is called at the very startup of Spacemacs initialization
before layers configuration.

#+BEGIN_SRC emacs-lisp :exports none
  (defun dotspacemacs/init ()
    "Initialization function.
  This function is called at the very startup of Spacemacs initialization
  before layers configuration.
  You should not put any user code in there besides modifying the variable
  values."
    ;; This setq-default sexp is an exhaustive list of all the supported
    ;; spacemacs settings.
    (setq-default
#+END_SRC

** Editing Style

One of `vim', `emacs' or `hybrid'. Evil is always enabled but if the
variable is `emacs' then the `holy-mode' is enabled at startup. `hybrid'
uses emacs key bindings for vim's insert mode, but otherwise leaves evil
unchanged. (default 'vim)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-editing-style 'hybrid
#+END_SRC

** Elpa
*** elpa-https

if non nil use HTTPS otherwise use HTTP. Default is t.

#+BEGIN_SRC emacs-lisp
  dotspacemacs-elpa-https t
#+END_SRC

*** elpa-timeout

Default is 5 seconds.

#+BEGIN_SRC emacs-lisp
  dotspacemacs-elpa-timeout 5
#+END_SRC

*** elpa-subdirectory

If non-nil, a form that evaluates to a package directory. For example, to
use different package directories for different Emacs versions, set this
to `emacs-version'.

#+BEGIN_SRC emacs-lisp
  dotspacemacs-elpa-subdirectory nil
#+END_SRC

** Startup Page
*** banner

Specify the startup banner. Default value is `official', it displays
the official spacemacs logo. An integer value is the index of text
banner, `random' chooses a random text banner in `core/banners'
directory. A string value must be a path to an image format supported
by your Emacs build.
If the value is nil then no banner is displayed. (default 'official)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-startup-banner 'official
#+END_SRC

*** lists

List of items to show in the startup buffer. If nil it is disabled.
Possible values are: `recents' `bookmarks' `projects'.
(default '(recents projects))

#+BEGIN_SRC emacs-lisp
  dotspacemacs-startup-lists '(recents projects)
#+END_SRC

*** recent list size

To configure the number of recent files to display in the home buffer

#+BEGIN_SRC emacs-lisp
  dotspacemacs-startup-recent-list-size 5
#+END_SRC

** Themes

List of themes, the first of the list is loaded when spacemacs starts.
Press <SPC> T n to cycle to the next theme in the list. (works great
with 2 themes variants, one dark and one light)

#+BEGIN_SRC emacs-lisp
    dotspacemacs-themes '(molokai
                          monokai)
#+END_SRC

** Cursor-Color

If non nil the cursor color matches the state color.

#+BEGIN_SRC emacs-lisp
  dotspacemacs-colorize-cursor-according-to-state t
#+END_SRC

** Font

Default font. `powerline-scale' allows to quickly tweak the mode-line
size to make separators look not too crappy.

#+BEGIN_SRC emacs-lisp
  dotspacemacs-default-font '("Source Code Pro"
                              :size 13
                              :weight bold
                              :width normal
                              :powerline-scale 1.1)
#+END_SRC

** Leader Keys
*** the leader key

#+BEGIN_SRC emacs-lisp
  dotspacemacs-leader-key "SPC"
#+END_SRC

*** emacs leader key

The leader key accessible in `emacs state' and `insert state'.
(default "M-m")

#+BEGIN_SRC emacs-lisp
  dotspacemacs-emacs-leader-key "M-m"
#+END_SRC

*** mode leader key

Major mode leader key is a shortcut key which is the equivalent of
pressing `<leader> m`. Set it to `nil` to disable it. (default ",")

#+BEGIN_SRC emacs-lisp
  dotspacemacs-major-mode-leader-key ","
#+END_SRC

*** major mode emacs leader key

Major mode leader key accessible in `emacs state' and `insert state'.
(default "C-M-m)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-major-mode-emacs-leader-key "C-M-m"
#+END_SRC

** Command Key

The command key used for Evil commands (ex-commands) and
Emacs commands (M-x).
By default the command key is `:' so ex-commands are executed like in Vim
with `:' and Emacs commands are executed with `<leader> :'.

#+BEGIN_SRC emacs-lisp
  dotspacemacs-command-key ":"
#+END_SRC

If non nil `Y' is remapped to `y$'. (default t)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-remap-Y-to-y$ t
#+END_SRC

** Auto-Save

Location where to auto-save files. Possible values are `original' to
auto-save the file in-place, `cache' to auto-save the file to another
file stored in the cache directory and `nil' to disable auto-saving.
(default 'cache)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-auto-save-file-location 'cache
#+END_SRC

** Ido

If non nil then `ido' replaces `helm' for some commands. For now only
`find-files' (SPC f f), `find-spacemacs-file' (SPC f e s), and
`find-contrib-file' (SPC f e c) are replaced. (default nil)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-use-ido nil
#+END_SRC

** Helm
*** helm resize

If non nil, `helm' will try to miminimize the space it uses. (default nil)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-helm-resize nil
#+END_SRC

*** helm header

if non nil, the helm header is hidden when there is only one source.
(default nil)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-helm-no-header nil
#+END_SRC

*** helm position

define the position to display `helm', options are `bottom', `top',
`left', or `right'. (default 'bottom)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-helm-position 'bottom
#+END_SRC

** Paste Micro-State

If non nil the paste micro-state is enabled. When enabled pressing `p`
several times cycle between the kill ring content. (default nil)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-enable-paste-micro-state nil
#+END_SRC

** Which-Key
*** delay

Which-key delay in seconds. The which-key buffer is the popup listing
the commands bound to the current keystroke sequence. (default 0.4)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-which-key-delay 0.4
#+END_SRC

*** position

Which-key frame position. Possible values are `right', `bottom' and
`right-then-bottom'. right-then-bottom tries to display the frame to the
right; if there is insufficient space it displays it at the bottom.
(default 'bottom)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-which-key-position 'bottom
#+END_SRC

** Loading Progress-Bar

If non nil a progress bar is displayed when spacemacs is loading. This
may increase the boot time on some systems and emacs builds, set it to
nil to boost the loading time. (default t)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-loading-progress-bar t
#+END_SRC

** Fullscreen
*** startup

If non nil the frame is fullscreen when Emacs starts up. (default nil)
(Emacs 24.4+ only)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-fullscreen-at-startup nil
#+END_SRC

*** toggle native

If non nil `spacemacs/toggle-fullscreen' will not use native fullscreen.
Use to disable fullscreen animations in OSX. (default nil)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-fullscreen-use-non-native nil
#+END_SRC

** Frame
*** startup

If non nil the frame is maximized when Emacs starts up.
Takes effect only if `dotspacemacs-fullscreen-at-startup' is nil.
(default nil) (Emacs 24.4+ only)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-maximized-at-startup nil
#+END_SRC

** Transparency
*** active

A value from the range (0..100), in increasing opacity, which describes
the transparency level of a frame when it's active or selected.
Transparency can be toggled through `toggle-transparency'. (default 90)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-active-transparency 90
 #+END_SRC

*** inactive

A value from the range (0..100), in increasing opacity, which describes
the transparency level of a frame when it's inactive or deselected.
Transparency can be toggled through `toggle-transparency'. (default 90)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-inactive-transparency 90
#+END_SRC

** Unicode

If non nil unicode symbols are displayed in the mode line. (default t)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-mode-line-unicode-symbols t
#+END_SRC

** Scrolling

If non nil smooth scrolling (native-scrolling) is enabled. Smooth
scrolling overrides the default behavior of Emacs which recenters the
point when it reaches the top or bottom of the screen. (default t)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-smooth-scrolling t
#+END_SRC

** Folding

Code folding method. Possible values are `evil' and `origami'.

#+BEGIN_SRC emacs-lisp
  dotspacemacs-folding-method 'origami
#+END_SRC

** Smartparens

If non-nil smartparens-strict-mode will be enabled in programming modes.
(default nil)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-smartparens-strict-mode nil
#+END_SRC

** Delimiters
*** highlight

Select a scope to highlight delimiters. Possible values are `any',
`current', `all' or `nil'. Default is `all' (highlight any scope and
emphasis the current one). (default 'all)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-highlight-delimiters 'all
#+END_SRC

** Server

If non nil advises quit functions to keep server open when quitting.
(default nil)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-persistent-server nil
#+END_SRC

** Search Tools

List of search tool executable names. Spacemacs uses the first installed
tool of the list. Supported tools are `ag', `pt', `ack' and `grep'.
(default '("pt" "ag" "ack" "grep"))

#+BEGIN_SRC emacs-lisp
  dotspacemacs-search-tools '("ag" "pt" "ack" "grep")
#+END_SRC

** Package Repository

The default package repository used if no explicit repository has been
specified with an installed package.
Not used for now. (default nil)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-default-package-repository nil
#+END_SRC
** Layout
*** default layout name

To set the name of the default Spacemacs layout.

#+BEGIN_SRC emacs-lisp
  dotspacemacs-default-layout-name "Main"
#+END_SRC

*** display default layout

To toggle display of the name of the default layout in the mode-line, default is
=nil=.

#+BEGIN_SRC emacs-lisp
  dotspacemacs-display-default-layout nil
#+END_SRC

*** auto resume layouts

To resume automatically the last layout when Emacs starts.

#+BEGIN_SRC emacs-lisp
  dotspacemacs-auto-resume-layouts nil
#+END_SRC

** Rollback
*** max rollback slots

To set the maximum number of rollback slots to keep in the cache.

#+BEGIN_SRC emacs-lisp
  dotspacemacs-max-rollback-slots 5
#+END_SRC

** Line Numbers

If non nil line numbers are turned on in all `prog-mode' and `text-mode'
derivatives. If set to `relative', also turns on relative line numbers.

#+BEGIN_SRC emacs-lisp
  dotspacemacs-line-numbers nil 
#+END_SRC

** Distinguish Gui Tab

If non nil then ~TAB~ and ~C-i~ are distinct using GUI Emacs, default is =nil=.

#+BEGIN_SRC emacs-lisp
  dotspacemacs-distinguish-gui-tab nil
#+END_SRC

** Whitespace Cleanup

To enable automatic cleanup of whitespace on save. Possible values are =all=,
=trailing=, =changed= or =nil=. Default is =changed=.

#+BEGIN_SRC emacs-lisp
;;  dotspacemacs-whitespace-cleanup changed 'changed
#+END_SRC

** Check For Update

to toggle check for Spacemacs updates at startup, default is =t=.

#+BEGIN_SRC emacs-lisp
  dotspacemacs-check-for-update t
#+END_SRC

#+BEGIN_SRC emacs-lisp :exports none
     ))
#+END_SRC


* LAYERS CONFIGURATION

Layers configuration declaration.

#+BEGIN_SRC emacs-lisp :exports none
  (defun dotspacemacs/layers ()
    "Configuration Layers declaration."
    (setq-default
#+END_SRC

** Distribution

Base distribution to use. This is a layer contained in the directory
`+distribution'. For now available distributions are `spacemacs-base'
or `spacemacs'. (default 'spacemacs)

#+BEGIN_SRC emacs-lisp 
  dotspacemacs-distribution 'spacemacs
#+END_SRC

** Layers

Use <SPC f e R> (Vim style) or <M-m f e R> (Emacs style) to install them.

*** ------------------------------
#+BEGIN_SRC emacs-lisp :exports none
  dotspacemacs-configuration-layers
  '(
#+END_SRC

*** + version-control
**** version-control

This layers adds general configuration for [[http://www.gnu.org/software/emacs/manual/html_node/emacs/Version-Control.html][Emacs VC]].
It should work with all VC backends such as Git, Mercurial, Bazaar, SVN, etc...

#+BEGIN_SRC emacs-lisp
  version-control
#+END_SRC

**** github

This layers adds support for [[http://github.com][Github]].

#+BEGIN_SRC emacs-lisp
  github
#+END_SRC
**** git

This layers adds extensive support for [[http://git-scm.com/][git]].

#+BEGIN_SRC emacs-lisp
  git
#+END_SRC

*** + lang
**** csv

This layer adds tools for better integration of CSV files in Spacemacs.

#+BEGIN_SRC emacs-lisp
  csv
#+END_SRC
**** asm

This layer adds support for Assembly code. The built-in major mode for
editing assembly code in Emacs is =asm-mode=.

The layer also adds =nasm-mode= for NASM-specific syntax. Although =nasm-mode=
is intended for NASM, it actually works well with other variants of Assembly
in general, and provides Imenu integration so you can jump around with ~SPC s j~.

_Features_:
- Improved syntax highlighting.
- Automatic indentation.
- Auto-completion for symbol in opened buffers.
- Look up documentation for current instruction at cursor.
- Imenu integration.

#+BEGIN_SRC emacs-lisp
  asm
#+END_SRC
**** ocalm

This is a very basic layer for editing ocaml files.

#+BEGIN_SRC emacs-lisp
  ocaml
#+END_SRC

**** Emacs-Lisp

This layer gathers all the configuration related to emacs-lisp. This should
always be in your dotfile, it is not recommended to uninstall it.

#+BEGIN_SRC emacs-lisp
  emacs-lisp
#+END_SRC

**** c-c++
This layer adds configuration for C/C++ language as well support for [[http://www.cmake.org/][CMake]]
scripts.

#+BEGIN_SRC emacs-lisp
  c-c++
#+END_SRC
**** go

This layer adds extensive support for go.

#+BEGIN_SRC emacs-lisp
  go
#+END_SRC

**** java

This layer adds support for the Java language using the [[http://eclim.org][Eclim]] client/server.

#+BEGIN_SRC emacs-lisp
  java
#+END_SRC

**** sql

This layer adds key bindings and configuration for =sql-mode=, which manages
interactive SQL buffers and highlights a wide range of SQL dialects.

#+BEGIN_SRC emacs-lisp
  sql
#+END_SRC

**** php

This layer adds PHP language support to Spacemacs.

#+BEGIN_SRC emacs-lisp
  php
#+END_SRC

**** html

This layer adds support for editing HTML and CSS.

#+BEGIN_SRC emacs-lisp
  html
#+END_SRC

**** python

This layer adds support for the Python language.

#+BEGIN_SRC emacs-lisp
  python
#+END_SRC

**** ruby

This layer aims at providing support for the Ruby language using
[[https://github.com/zenspider/enhanced-ruby-mode][enh-ruby-mode]] and [[https://github.com/dgutov/robe][robe-mode]].

#+BEGIN_SRC emacs-lisp
  ruby
#+END_SRC

**** clojure

This layer adds support for [[http://clojure.org][Clojure]] language using [[https://github.com/clojure-emacs/cider][CIDER]].

#+BEGIN_SRC emacs-lisp
  clojure
#+END_SRC

**** latex

This layer adds support for LaTeX files with [[https://savannah.gnu.org/projects/auctex/][AucTeX]].

#+BEGIN_SRC emacs-lisp
  latex
#+END_SRC
**** yaml

This layer provides syntax highlighting for YAML files.

#+BEGIN_SRC emacs-lisp
  yaml
#+END_SRC

**** markdown

This layer adds markdown support to Spacemacs.

#+BEGIN_SRC emacs-lisp
  markdown
#+END_SRC

**** javascript

This layer adds support for the JavaScript language using [[https://github.com/mooz/js2-mode][js2-mode]].

#+BEGIN_SRC emacs-lisp
  javascript
#+END_SRC

**** flow-type

This layer adds some [[https://flowtype.org/][flow]] related functionality to Emacs:
 - Show the flow-type of the object under the cursor using Eldoc
 - Add flow checking to flycheck (based on the flycheck-flow package)
 - company-mode completion using company-flow

#+BEGIN_SRC emacs-lisp
  flow-type
#+END_SRC

**** typescript

This layer adds support for TypeScript and TSX editing.

This layer provides:
- Eldoc-mode
- Documentation at point
- Auto complete
- Flycheck with linter
- Jump to definition, Jump to type definition
- Find occurrences (Imenu-mode)
- Rename symbol
- tsx mode
- formatting
- TypeScript playground integration

#+BEGIN_SRC emacs-lisp
  typescript
#+END_SRC

*** + frameworks
**** django

This layer adds support for the Python [[https://www.djangoproject.com/][Django]] framework via [[https://github.com/davidmiller/pony-mode][pony-mode]].

#+BEGIN_SRC emacs-lisp
  django
#+END_SRC

**** react

ES6 and JSX ready configuration layer for React.
It will automatically recognize =.jsx= and =.react.js= files.

#+BEGIN_SRC emacs-lisp
  react
#+END_SRC

*** + chat 
**** slack

This layer provides an interface to the Slack chat service via the emacs-slack
package. Where possible, this layer aims to reuse keybindings from the IRC
packages in Spacemacs.

#+BEGIN_SRC emacs-lisp
  slack
#+END_SRC

**** erc

Layer for [[http://www.emacswiki.org/emacs/ERC][ERC IRC chat]].

#+BEGIN_SRC emacs-lisp
  erc
#+END_SRC

**** jabber

This layer adds keybindings for jabber.el. jabber.el is a Jabber (XMPP) client for Emacs.

#+BEGIN_SRC emacs-lisp
  jabber
#+END_SRC

*** + tools
**** dash

- [[http://kapeli.com/dash][dash]] :: Is a great tool for quick access to various sets of documentation,
          only available in OS X.

- [[https://github.com/stanaka/dash-at-point][dash-at-point]] :: Is the package used to integrate =dash= in Emacs. It will try
                   to intelligently guess specific docsets to use based off of
                   your current mode.

- [[http://zealdocs.org/][zeal]] :: Zeal is an offline documentation browser inspired by Dash,
          available for Linux and Windows.

- [[https://github.com/jinzhu/zeal-at-point][zeal-at-point]] :: Run zeal-at-point to search the word at point (or string in
                   region), then Zeal is launched and search the word. Use
                   prefix argument C-u to edit the search string first.

#+BEGIN_SRC emacs-lisp
  dash
#+END_SRC

**** vagrant

This layer adds support for working with Vagrant using [[https://github.com/ottbot/vagrant.el][vagrant.el]] and
[[https://github.com/dougm/vagrant-tramp][vagrant-tramp]].

#+BEGIN_SRC emacs-lisp
  vagrant
#+END_SRC

**** pdf-tools

This layer enables support for the [[https://github.com/politza/pdf-tools][pdf-tools]] package.

According to the official repository:

#+begin_quote
"PDF Tools is, among other things, a replacement of DocView for PDF files. The
key difference is, that pages are not pre-rendered by e.g. ghostscript and
stored in the file-system, but rather created on-demand and stored in memory."
#+end_quote

Examples of features that =pdf-tools= provides:
- Use =occur= in the pdf file;
- Show all headings in a outline buffer;
- Manipulate annotations.

#+BEGIN_SRC emacs-lisp
  pdf-tools
#+END_SRC

**** rebox


This layer adds support for [[https://github.com/lewang/rebox2][rebox2]] package which is a minor-mode allowing
to easily add ASCII text boxes to a buffer.

A nice video demonstration by the package author can be found [[https://www.youtube.com/watch?v=53YeTdVtDkU][here]].

#+BEGIN_SRC emacs-lisp
  rebox
#+END_SRC

**** docker

This layer provides syntax highlighting and build functionality for Docker files
as well as TRAMP access to running docker containers.

It also includes basic Docker container and image management provided by
[[https://github.com/Silex/docker.el][docker.el.]]

#+BEGIN_SRC emacs-lisp
  docker
#+END_SRC
**** terraform
This layer provides syntax support for Terraform `.tf` files using
[[https://github.com/syohex/emacs-terraform-mode][terraform-mode]].

#+BEGIN_SRC emacs-lisp
  terraform
#+END_SRC
**** nginx

[[https://github.com/ajc/nginx-mode][nginx-mode]] for editing [[http://nginx.org][nginx]] configuration files.
It adds basic syntax highlighting and syntax-aware tabbing.

#+BEGIN_SRC emacs-lisp
  nginx
#+END_SRC
**** pandoc

This layer adds support for [[http://johnmacfarlane.net/pandoc][Pandoc]].

Pandoc is a universal document converter. It makes it easy to e.g. convert a
Markdown file to org mode or vice versa. It can also export your text to PDF or
DOCX.

This layer automatically install an org exporter using the [[https://github.com/kawabata/ox-pandoc][ox-pandoc]].

#+BEGIN_SRC emacs-lisp
  pandoc
#+END_SRC

**** geolocalisation

This layer offers few location sensitive adjustment to Emacs, such as
automatically switching between light (day) and dark (night) themes, weather
forecast and on OS X, also automatic tracking of location, using OS X's
CoreLocation services.

#+BEGIN_SRC emacs-lisp
  (geolocation :variables
               geolocation-enable-osx-location-service-support t
               geolocation-enable-weather-forecast t
               geolocation-enable-automatic-theme-changer nil)
#+END_SRC

*** + vim
**** vim-empty-lines

This layer is a drop-in replacement for the =vi-tilde-fringe= mode, for those
who desire behaviour closer to =vim='s.

It has better compatibility with retina displays, as it uses a text overlay
using your font, rather than a pixel-art tilde. The empty line indicators are
overlaid in within the buffer as in =vim=, and not in the fringe. The indicator
behaviour with trailing empty lines matches =vim='s behaviour.

For details, see the [[https://github.com/jmickelin/vim-empty-lines-mode][vim-empty-lines-mode]] repository.   

#+BEGIN_SRC emacs-lisp
  vim-empty-lines
#+END_SRC

**** vinegar

This layer is a port contribution layer for vim-vinegar for emacs.

A port of tpope's vinegar.vim [[https://github.com/tpope/vim-vinegar][vinegar]], simplifying =dired= with a limited number
of details and exposing the ~-~ command in all buffers to enter dired.

#+BEGIN_SRC emacs-lisp
  vinegar
#+END_SRC

*** + email
**** mu4e

mu4e is an emacs-based e-mail client. It’s based on the mu e-mail
indexer/searcher. It attempts to be a super-efficient tool to withstand the
daily e-mail tsunami.

#+BEGIN_SRC emacs-lisp
  mu4e
#+END_SRC

*** + custom
**** 42

42 layer.

#+BEGIN_SRC emacs-lisp
  ;; fortytwo
#+END_SRC
*** + os
**** osx

While this layer enables common OSX bindings, it does not implement OSX
navigation keybindings. Spacemacs is meant to be used with evil, and we
encourage you to do so :)

#+BEGIN_SRC emacs-lisp
  osx
#+END_SRC

*** + completion
**** auto-completion

This layer provides auto-completion to Spacemacs.
The following completion engines are supported:
- [[http://company-mode.github.io/][company]]
- [[http://auto-complete.org/][auto-complete]]

Snippets are supported via [[https://github.com/capitaomorte/yasnippet][yasnippet]] and [[https://github.com/abo-abo/auto-yasnippet][auto-yasnippet]].
This layer also configures =hippie-expand=.

#+BEGIN_SRC emacs-lisp
  (auto-completion :variables
                   auto-completion-return-key-behavior 'complete
                   auto-completion-tab-key-behavior 'cycle
                   auto-completion-complete-with-key-sequence nil
                   auto-completion-private-snippets-directory "~/.spacemacs.d/snippets")
#+END_SRC

*** + emacs
**** better-defaults

This layer enhances the default commands of Emacs and is primarily intended to
be used with the =emacs= editing style as it does not change anything in the Vim
key bindings.

However the =emacs= editing style is not required, you can still use this layer
while you are using the =vim= editing style if you have some kind of mixed
style.

The commands defined in this layer are taken from various sources like [[https://github.com/bbatsov/prelude][Prelude]].

#+BEGIN_SRC emacs-lisp
  better-defaults
#+END_SRC

**** semantic

CEDET is a *C*ollection of *E*macs *D*evelopment *E*nvironment *T*ools written
with the end goal of creating an advanced development environment in Emacs.
CEDET includes common features such as intelligent completion, source code
navigation, project management, code generation with templates. CEDET also
provides a framework for working with programming languages; support for new
programming languages can be added and use CEDET to provide IDE-like features.
This framework is called Semantic.

#+BEGIN_SRC emacs-lisp
  semantic
#+END_SRC

Semantic is a package that provides a framework for writing parsers. Parsing is
a process of analyzing source code based on programming language syntax. The
packages relies on Semantic for analyzing source code and uses its results to
perform smart code refactoring that based on code structure of the analyzed
language, instead of plain text structure. Semantic is the core of CEDET.

**** org

#+BEGIN_SRC emacs-lisp
  org
#+END_SRC

This layer enables  [[http://orgmode.org/][org mode]] for Spacemacs.

*** + pair-programming
**** floobits

This layer adds support for peer programming tool [[https://github.com/Floobits/floobits-emacs][floobits]].

#+BEGIN_SRC emacs-lisp
  floobits
#+END_SRC

*** + themes
**** colors

This layer colors your life with:
- [[https://github.com/Fanael/rainbow-identifiers][rainbow identifiers]] mode will colorize each variables and functions with an
  almost unique color. The keywords and the declaration of function colors are
  disabled in order to make the colorized variables and functions stand out.
- [[https://julien.danjou.info/projects/emacs-packages][rainbow mode]] displays strings representing colors with the color they
  represent as background.
- [[https://github.com/syl20bnr/nyan-mode][nyan mode]] display a Nyan cat progress bar in the mode-line.

#+BEGIN_SRC emacs-lisp
  (colors :variables
          ;; colors-enable-rainbow-identifiers t
          ;; colors-enable-nyan-cat-progress-bar t
          )
#+END_SRC

**** themes-megapack (disabled)

This simple contribution layer is an example. It installs around 100 themes
for Emacs. You can try them easily by invoking helm-themes with: ~<SPC> T h~.

#+BEGIN_SRC emacs-lisp
  ;; themes-megapack
#+END_SRC

*** + tags
**** cscope
This layer provides bindings for using [[http://cscope.sourceforge.net][Cscope]] and [[https://github.com/portante/pycscope][PyCscope]] in Spacemacs.

=Cscope= provides indexing and searching capabilities for C and C++ code.
=PyCscope= extends these capabilities for Python code as well. See
[[https://github.com/OpenGrok/OpenGrok/wiki/Comparison-with-Similar-Tools][here]] for a comparison between =Cscope= and other similar tools (such as gtags).

#+BEGIN_SRC emacs-lisp
  cscope
#+END_SRC

*** + checkers
**** spell-checking

This layer provides spell checking using [[http://www-sop.inria.fr/members/Manuel.Serrano/flyspell/flyspell.html][Flyspell]].

#+BEGIN_SRC emacs-lisp
  spell-checking
#+END_SRC
**** syntax-checking

This layer provides on the fly syntax checking using [[http://www.flycheck.org/][Flycheck]].

#+BEGIN_SRC emacs-lisp
  syntax-checking
#+END_SRC

*** + web-services
**** wakatime (disabled)

This layer adds support for Wakatime.

WakaTime was built to solve time tracking for programmers.
Since we work inside a text editor, why should we have to start and stop a
timer? WakaTime uses open-source text editor plugins to automatically track the
time you spend programming so you never have to manually track it again!

#+BEGIN_SRC emacs-lisp
;;  wakatime
#+END_SRC

**** restclient

This is a package that lets you have a REPL-like interface
for http requests. Full documentation and examples can be found in the
package's [[https://github.com/pashky/restclient.el][GitHub Page]].

#+BEGIN_SRC emacs-lisp
  restclient
#+END_SRC

**** finance

This layer adds finance related packages.

#+BEGIN_SRC emacs-lisp
  finance
#+END_SRC

**** deft

[[http://jblevins.org/projects/deft/][Deft]] is an Emacs mode inspired by =Notational Velocity= for quickly
browsing and creating notes.

#+BEGIN_SRC emacs-lisp
  deft
#+END_SRC

**** shell
This layer configures the various shells available in Emacs.

#+BEGIN_SRC emacs-lisp
  (shell :variables
         shell-default-height 30
         shell-default-position 'bottom
         shell-default-shell 'term
         shell-default-term-shell "zsh")
#+END_SRC

*** ------------------------------
#+BEGIN_SRC emacs-lisp :exports none
  )   
#+END_SRC

** Layer Path

List of additional paths where to look for configuration layers.
Paths must have a trailing slash (i.e. `~/.mycontribs/')

#+BEGIN_SRC emacs-lisp
  dotspacemacs-configuration-layer-path '("~/.spacemacs.d/layers/")
#+END_SRC

** Layers Dependencies

This section list all dependencies needed by the configuration.

*** brew

brew dependencies

#+BEGIN_SRC sh
  brew install ledger pt ispell poppler
#+END_SRC

*** NPM

npm dependencies.

#+BEGIN_SRC bash
  npm i -g npm tern js-beautify
#+END_SRC

*** GO

go dependencies

#+BEGIN_SRC bash
  go get -u -v github.com/nsf/gocode
  go get -u -v github.com/rogpeppe/godef
  go get -u -v golang.org/x/tools/cmd/oracle
  go get -u -v golang.org/x/tools/cmd/gorename
#+END_SRC

*** environment

You will also have to help pkg-config find some libraries by setting PKG_CONFIG_PATH

#+BEGIN_SRC sh
  export PKG_CONFIG_PATH=/usr/local/Cellar/zlib/1.2.8/lib/pkgconfig:/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig
#+END_SRC

** Packages
*** additional packages

List of configuration layers to load. If it is the symbol `all' instead
of a list then all discovered layers will be installed.
List of additional packages that will be installed without being
wrapped in a layer. If you need some configuration for these
packages then consider to create a layer, you can also put the
configuration in `dotspacemacs/config'.

**** ------------------------------
#+BEGIN_SRC emacs-lisp :exports none
dotspacemacs-additional-packages '(
#+END_SRC

**** orgbabel

list of additional OB support

***** go

 Org-Babel support for evaluating go source code.

#+BEGIN_SRC emacs-lisp
  ob-go
#+END_SRC

***** shell

 Org-Babel support for evaluating shell source code.

***** restclient

 Org-Babel support for evaluating restclient source code.

 #+BEGIN_SRC emacs-lisp
   ob-restclient
 #+END_SRC

***** php

 Org-Babel support for evaluating php source code.

#+BEGIN_SRC emacs-lisp
  ob-php
#+END_SRC

**** editorconfig

This is an EditorConfig plugin for Emacs.

#+BEGIN_SRC emacs-lisp
  editorconfig
#+END_SRC

**** jira

Use Jira in Emacs org-mode.

#+BEGIN_SRC emacs-lisp
  jira
  org-jira
  jira-markup-mode
#+END_SRC

**** edbi

This program connects the database server through Perl's DBI, and provides
DB-accessing API and the simple management UI.

#+BEGIN_SRC emacs-lisp
  edbi
#+END_SRC

**** bookmark+

The internal bookmark format (data structure) used by Bookmark+ is compatible
with that of vanilla GnuEmacs. It extends that structure in new ways, to
accommodate new bookmark types.

#+BEGIN_SRC emacs-lisp
   bookmark+
#+END_SRC

**** skeletor

=Skeletor= provides project templates for Emacs. It also automates the mundane
parts of setting up a new project like version control, licenses and tooling.

=Skeletor= comes with a number of predefined templates and allows you to easily
create your own.

#+BEGIN_SRC emacs-lisp
  skeletor
#+END_SRC

**** ssh tunnels

This package lets you run and kill SSH tunnels. 
Set the variable ssh-tunnels-configurations, e.g.:

#+BEGIN_SRC emacs-lisp :startup nohideblocks :tangle no
  (setq ssh-tunnels-configurations
        '((:name "my tunnel"
                 :local-port 1234
                 :remote-port 3306
                 :login "me@host")))
#+END_SRC

#+BEGIN_SRC emacs-lisp
  ssh-tunnels
#+END_SRC

**** impatient mode

impatient-mode is a minor mode that publishes the live buffer through the local
simple-httpd server under /imp/<buffer-name>. To unpublish a buffer, toggle
impatient-mode off.

#+BEGIN_SRC emacs-lisp
  impatient-mode
#+END_SRC

**** simple httpd

A simple Emacs web server.

#+BEGIN_SRC emacs-lisp
  simple-httpd
#+END_SRC

**** ------------------------------
#+BEGIN_SRC emacs-lisp :exports none
)
#+END_SRC

*** excluded packages

A list of packages and/or extensions that will not be install and loaded.

#+BEGIN_SRC emacs-lisp
  dotspacemacs-excluded-packages '(drupal-mode)
#+END_SRC

*** orphan-packages 

If non-nil spacemacs will delete any orphan packages, i.e. packages that
are declared in a layer which is not a member of
the list `dotspacemacs-configuration-layers'. (default t)

#+BEGIN_SRC emacs-lisp
  dotspacemacs-delete-orphan-packages t
#+END_SRC

#+BEGIN_SRC emacs-lisp :exports none
))
#+END_SRC


* USER CONFIGURATION

User configuration declaration.

** User Initialization

Initialization function for user code. It is called immediately after
`dotspacemacs/init'.

#+BEGIN_SRC emacs-lisp :exports none
  (defun dotspacemacs/user-init ()
    "Initialization function for user code.
  It is called immediately after `dotspacemacs/init'."
#+END_SRC

*** ------------------------------

*** TODO 

*** ------------------------------
#+BEGIN_SRC emacs-lisp :exports none
    )
#+END_SRC

** User Configuration

Configuration function for user code. This function is called at the very end of
Spacemacs initialization after layers configuration.

#+BEGIN_SRC emacs-lisp :exports none
  (defun dotspacemacs/user-config ()
    "Configuration function for user code.
       This function is called at the very end of Spacemacs initialization after
       layers configuration."
#+END_SRC

*** ------------------------------
*** keys
**** find-files

Switch to spacemacs/helm-find-file.

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x C-f") 'spacemacs/helm-find-files)
#+END_SRC

**** buffer-switch

Switch to spacemacs/helm-find-file.

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x b") 'helm-mini)
#+END_SRC

**** buffer-kill-current

Kill current buffers.

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x k") 'ido-kill-buffer)
#+END_SRC

**** buffer-reload

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x C-v") 'spacemacs/safe-revert-buffer)
#+END_SRC

*** Auto Mode Alist
**** Smarty

handle files ending in '.tpl'.

#+BEGIN_SRC emacs-lisp
  (add-to-list 'auto-mode-alist '("\\.tpl$" . web-mode))
#+END_SRC

**** Env

handle files ending in '.env'.

#+BEGIN_SRC emacs-lisp
  (add-to-list 'auto-mode-alist '("\\.env$" . conf-mode))
#+END_SRC

**** JavaScript


#+BEGIN_SRC emacs-lisp
  (add-to-list 'auto-mode-alist '("\\.jsx?$" . react-mode))
#+END_SRC

*** EditorConfig

Always enable EditorConfig.

#+BEGIN_SRC emacs-lisp
  (editorconfig-mode 1)
#+END_SRC

*** regexp

I prefer to use PCRE REGEX engine instead.

#+BEGIN_SRC emacs-lisp
  (pcre-mode)
  (custom-set-variables
           '(vr/engine (quote pcre2el)))
#+END_SRC

*** Origami

Enable Origami globally

#+BEGIN_SRC emacs-lisp
  (global-origami-mode t)
#+END_SRC

*** PowerLine

Set `Powerline' default separator to arrow.

#+BEGIN_SRC emacs-lisp
  (setq powerline-default-separator 'bar)
#+END_SRC

*** Sunshine (weather forecast)

Switch to metric.

#+BEGIN_SRC emacs-lisp
  (setq sunshine-units 'metric)
#+END_SRC

Weather forecast icons can be toggled by pressing `i' within this mode's main
buffer.

#+BEGIN_SRC emacs-lisp
  (setq sunshine-show-icons t)
#+END_SRC

*** NeoTree

Set the NeoTree Theme to Nerd

#+BEGIN_SRC emacs-lisp
  (setq neo-theme 'nerd)
#+END_SRC

*** Skeletor

=Skeletor= provides project templates for Emacs. It also automates the mundane
parts of setting up a new project like version control, licenses and tooling.
=Skeletor= comes with a number of predefined templates and allows you to easily
create your own.

#+BEGIN_SRC emacs-lisp
  (setq skeletor-project-directory "~/.spacemacs.d/project-skeletons")
#+END_SRC

*** Deft

#+BEGIN_SRC emacs-lisp
  (setq deft-directory "~/Dropbox/notes")
#+END_SRC

*** Projectile

Once you have selected your project, the top-level directory
of the project is immediately opened for you in a dired buffer.

#+BEGIN_SRC emacs-lisp
  (setq projectile-switch-project-action 'projectile-dired)
#+END_SRC

Make projectile work with tramp mode.
 
#+BEGIN_SRC emacs-lisp
  (defadvice projectile-project-root (around ignore-remote first activate)
      (unless (file-remote-p default-directory) ad-do-it))
#+END_SRC

*** windmove

Windmove lets you move point from window to window using Shift and the arrow keys.

#+BEGIN_SRC emacs-lisp
  (when (fboundp 'windmove-default-keybindings)
    (windmove-default-keybindings))
#+END_SRC

Make windmove work in org-mode.

#+BEGIN_SRC emacs-lisp
  (add-hook 'org-shiftup-final-hook 'windmove-up)
  (add-hook 'org-shiftleft-final-hook 'windmove-left)
  (add-hook 'org-shiftdown-final-hook 'windmove-down)
  (add-hook 'org-shiftright-final-hook 'windmove-right)
#+END_SRC

*** ------------------------------
#+BEGIN_SRC emacs-lisp :exports none
    )
#+END_SRC


