(require 'org)
(let* ((dotspacemacs-basedir (file-name-directory (or load-file-name buffer-file-name)))
      (dotspacemacs-config-file (concat dotspacemacs-basedir "gfanton.org"))
      (dotspacemacs-custom-file (concat dotspacemacs-basedir "custom.el")))
  (unless (file-exists-p dotspacemacs-custom-file)
    (write-region "" nil dotspacemacs-custom-file))
  (setq custom-file dotspacemacs-custom-file)
  (org-babel-load-file dotspacemacs-config-file)
  (load dotspacemacs-custom-file))
